import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Script from 'next/script';
import Image from 'next/image';
const inter = Inter({ subsets: ['latin'] });
import { Baloo_2 } from 'next/font/google';
const Baloo = Baloo_2({ subsets: ['latin'], weight: '400', variable: '--font-Baloo_2' });
export const metadata: Metadata = {
  title: 'Developios - Brand First CRO Agency',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script id="clarity-script">
          {` (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "kt2cjpnwo0");`}
        </Script>
        <Script async src="https://www.googletagmanager.com/gtag/js?id=G-M6ZR4FXGPZ"></Script>
        <Script id="g4A-script">
          {` window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-M6ZR4FXGPZ');
  `}
        </Script>

        <Script id="meta-pixel">
          {`!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '374119275263528');
fbq('track', 'PageView');`}
        </Script>
        {/* <noscript>
          <Image
            alt="meta"
            height="1"
            width="1"
            style={{ display: 'none' }}
            src="https://www.facebook.com/tr?id=374119275263528&ev=PageView&noscript=1"
          />
        </noscript> */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
