import type { Metadata } from "next";
import { Inter, Baloo_2 } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const Baloo = Baloo_2({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-Baloo_2",
});

export const metadata: Metadata = {
  title: "Archway Electric",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
